### ISSUE TITLE
rmitm

### ISSUE THREAD

**Issue by bkarthick** [marcyb/rmitm#2]
How to config the RMITM proxy in calabash-ios. Can you share detail steps to config the RMITM proxy in the calabash.

**Comment by marcyb** [comment]
Hi,

RMITM is not a proxy, it is a collection of Ruby utilities that enable control of mitmdump (written in Python) from Ruby. I'm not sure exactly what you are trying to achieve but your best source of help is probably the [calabash-ios google group](https://groups.google.com/forum/#!forum/calabash-ios).

Cheers,

M
