### ISSUE TITLE
issues with MitmFlowArray 

### ISSUE THREAD

**Issue by anilab** [marcyb/rmitm#3]
Hello ,,

I have got a dump file but when I tried to read the data in ruby  it is throwing some error .
f = MitmFlowArray.from_file(proxy('p1').dumpfile) 

---

******\* Error returned from readFromFlow python script:

---

Traceback (most recent call last):
 File "/Library/Ruby/Gems/2.0.0/gems/rmitm-0.0.5/bin/readFromFlow", line 3, in <module>
   from libmproxy import flow
ImportError: No module named libmproxy

---

Does it require any extra libraries as i'm using only one library for this "require rmitm"  ?? 

Thanks in advance !!

**Comment by marcyb** [comment]
Hi,

readFromFlow is a python script that uses the libmproxy module in mitmproxy. Please check your mitmproxy installation and/or python environment setup.

Cheers,

M

**Comment by DineshKumar7** [comment]
Hi Marc,

I am trying to use mitmproxy in ubuntu and while staring [proxy('p1').start] the mitmproxy using rmitm - Iam getting the error (check below for error message). However I am not getting error if I start the mitmproxy normally. Can you please let me know what went wrong and how to resolve this. Thanks
- Cannot start mitmdump on port 8081 - port unavailable (RuntimeError)
  /var/lib/gems/1.9.1/gems/rmitm-0.0.5/lib/mitmdump.rb:99:in `start'
  /home/xxx/xxx/xxx/xxx/support/app_installation_hooks.rb:10:in`Before'

**Comment by marcyb** [comment]
Hi Dinesh,

This is most likely due to a bug in the port_available? method in the Mitmdump class. Replace with the following and it should work for you (it did for me):

``` ruby
    def port_available?
        system("nc -z 127.0.0.1 #{@port}")
        !$?.success?
    end
```

Regards

Marc
